
trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - name: serviceConnectionName
    value: 'EVENT DRIVEN SP'
  - name: backendAzureRmResourceGroupName
    value: 'rg-datasynchro-iac'
  - name: backendAzureRmResourceGroupLocation
    value: 'westeurope'
  - name: backendAzureRmStorageAccountName
    value: 'stdatasynchroiac' 
  - name: backendResourceContainerName
    value: 'backend-tfstate-spokes'
  - name: repositoryName
    value: 'lortcslogcorner'
  - name: imageName
    value: 'dockeragent'
  - name: BUILD_NUMBER
    value: '$(Build.BuildId)'
  - name : AZP_URL
    value : 'https://dev.azure.com/logcornerworkshop'
  - name: AZP_POOL
    value: 'DOCKER-AGENTS'
 
stages:
  - template: templates/deploy_powershell.yml
    parameters:
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      resourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
      resourceGroupLocation:  ${{ variables.backendAzureRmResourceGroupLocation }} 
      storageAccountName: ${{ variables.backendAzureRmStorageAccountName }} 
      workspace:  'dev' 
      stageName: 'backend_storage_account'
  
  - template: templates/deploy_terraform.yml
    parameters:
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      backendAzureRmResourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
      backendAzureRmStorageAccountName:  ${{ variables.backendAzureRmStorageAccountName }} 
      backendResourceContainerName :  ${{ variables.backendResourceContainerName }}
      workspace:  'dev' 
      stageName: 'container_registry'
      targetModule : 'module.container_registry'
      VARS: '-var-file="dev.tfvars" -var "build_number=${{ variables.BUILD_NUMBER }}" -var "AZP_TOKEN=none" -var "AZP_URL=none" -var "AZP_POOL=none}" '
  - template: templates/docker_build.yml
    parameters:
      BUILD_NUMBER:  ${{ variables.BUILD_NUMBER }}
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      repository: ${{ variables.repositoryName }}
      imageName: ${{ variables.imageName }}
  - template: templates/deploy_terraform.yml
    parameters:
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      backendAzureRmResourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
      backendAzureRmStorageAccountName:  ${{ variables.backendAzureRmStorageAccountName }} 
      backendResourceContainerName :  ${{ variables.backendResourceContainerName }}
      workspace:  'dev' 
      stageName: 'container_instance'
      targetModule : 'module.container_instance'
      VARS: '-var-file="dev.tfvars" -var "build_number=${{ variables.BUILD_NUMBER }}" -var "AZP_TOKEN=$(AZP_TOKEN)" -var "AZP_URL=${{ variables.AZP_URL }}" -var "AZP_POOL=${{ variables.AZP_POOL }}"'