
trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - name: serviceConnectionName
    value: 'EVENT DRIVEN SP'
  - name: backendAzureRmResourceGroupName
    value: 'rg-datasynchro-iac'
  - name: backendAzureRmResourceGroupLocation
    value: 'westeurope'
  - name: backendAzureRmStorageAccountName
    value: 'stdatasynchroiac' 
  - name: backendResourceContainerName
    value: 'backend-tfstate-spokes'
  - name: BUILD_NUMBER
    value: '$(Build.BuildId)'
  # - name : AZP_URL
  #   value : 'https://dev.azure.com/logcornerworkshop'
 
stages:
  - template: templates/deploy_powershell.yml
    parameters:
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      resourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
      resourceGroupLocation:  ${{ variables.backendAzureRmResourceGroupLocation }} 
      storageAccountName: ${{ variables.backendAzureRmStorageAccountName }} 
      workspace:  'dev' 
      stageName: 'hub'
  
  - template: templates/deploy_terraform.yml
    parameters:
      serviceConnectionName:  ${{ variables.serviceConnectionName }}
      backendAzureRmResourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
      backendAzureRmStorageAccountName:  ${{ variables.backendAzureRmStorageAccountName }} 
      backendResourceContainerName :  ${{ variables.backendResourceContainerName }}
      workspace:  'dev' 
      stageName: 'spoke'
      VARS: '-var-file="dev.tfvars" '
  # - template: templates/build.yml
  #   parameters:
  #     BUILD_NUMBER:  ${{ variables.BUILD_NUMBER }}
  #     serviceConnectionName:  ${{ variables.serviceConnectionName }}
  #     repository: 'lortcslogcorner'
  #     imageName: 'dockeragent'
  # - template: templates/deploy.yml
    # parameters:
    #   BUILD_NUMBER:  ${{ variables.BUILD_NUMBER }}
    #   serviceConnectionName:  ${{ variables.serviceConnectionName }}
    #   backendAzureRmResourceGroupName:  ${{ variables.backendAzureRmResourceGroupName }}
    #   backendAzureRmStorageAccountName:  ${{ variables.backendAzureRmStorageAccountName }} 
    #   backendResourceContainerName :  'backend-tfstate-hub-devops'
    #   workspace:  'dev' 
    #   subfolder:   'iac/hub/devops'
    #   stageName: 'devops'
    #   VARS: '-var-file="dev.tfvars" -var "build_number=$(Build.BuildId)" -var "AZP_TOKEN=$(personalAccessToken)" -var "AZP_URL=${{ variables.AZP_URL }}"'